# Numpy讲解

Numpy是python的开源的数值计算的扩展。
可用来存储和处理大型矩阵，比Python自身数据结构要高效。
Numpy将python变成一种免费的强大的Matlab系统。


numpy其核心为N维数组对象，称为ndarray对象。   
包含三种方法创建一个ndarray对象，    
1.由list转换而来。   
2.借助numpy提供的函数构造ndarray对象    
3.读文件生成。   

numpy的官方帮助文档
https://numpy.org.cn/article/basics/different_ways_create_numpy_arrays.html

step1：安装numpy

In [2]:
%conda install numpy

Solving environment: ...working... done

# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.


step2：第一种方法：由list直接转换ndarray对象

numpy.array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0, like=None)


object：接受对象,
dtype：数据类型,
ndmin：维度，默认是0维.

In [1]:
import numpy  as np
array_1 =np.array([1,2,3])
print(array_1)

[1 2 3]


step3：查看相应的属性

In [6]:
#查看数据类型
print(type(array_1))

#二维数据
array_2 = np.array([[1,2,3],[4,5,6]])
print(array_2)

#查看他的形状
print(array_2.shape)
#查看维度
print(array_2.ndim)

<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]
(2, 3)
2


创建二维数组

In [2]:
import numpy  as np
# 创建二维数组
arr2 = np.array([[1, 2, 3, 4],[4, 5, 6, 7], [7, 8, 9, 10]])
print('创建的数组为：\n', arr2)

print('数组维度为：', arr2.shape)  # 查看数组结构
print('数组类型为：', arr2.dtype)  # 查看数组类型
print('数组元素个数为：', arr2.size)  # 查看数组元素个数
print('数组每个元素大小为：', arr2.itemsize)  # 查看数组每个元素大小

创建的数组为：
 [[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]
数组维度为： (3, 4)
数组类型为： int32
数组元素个数为： 12
数组每个元素大小为： 4


step4：第二种方法，利用numpy函数创建adarray对象

1.利用anrange创建三维数组

reshape(2,4,3)表示有个2个四行三列的二维数组

In [7]:
array = np.arange(24).reshape(2,4,3)
print(array)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


2.使用其他Numpy函数
除了arange函数之外，你还可以使用其他有用的函数（如 zeros 和 ones）来快速创建和填充数组。
使用zeros函数创建一个填充零的数组。函数的参数表示行数和列数（或其维数）。

In [8]:
arr6=np.zeros((2,4))
print(arr6)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


用1填充

In [ ]:
arr7=np.ones((3,4))
print(arr7)

full函数创建一个填充给定值的n * n数组。

In [11]:
arr7=np.full((2,3,4),6)
print(arr7)

[[[6 6 6 6]
  [6 6 6 6]
  [6 6 6 6]]

 [[6 6 6 6]
  [6 6 6 6]
  [6 6 6 6]]]


函数linspace在指定的时间间隔内返回均匀间隔的数字。 例如，下面的函数返回0到10之间的四个等间距数字。

In [4]:
import numpy  as np
np.linspace(0, 10, num=5,dtype=int)

array([ 0,  2,  5,  7, 10])

你还可以使用特殊库函数来创建数组。例如，要创建一个填充0到1之间随机值的数组，请使用random函数。这对于需要随机状态才能开始的问题特别有用。

In [5]:
np.random.random((2,2))

array([[0.75955831, 0.78583813],
       [0.10995654, 0.79392177]])

In [6]:
# 代码 2-14
print('生成的随机数组为：\n', np.random.random(100))

# 代码 2-15
print('生成的随机数组为：\n', np.random.rand(10,5))

# 代码 2-16
print('生成的随机数组为：\n', np.random.randn(10,5))

# 代码 2-17
print('生成的随机数组为：\n', np.random.randint(2, 10, size=[2,5]))

生成的随机数组为：
 [0.87948804 0.93065765 0.40102537 0.29482184 0.63365458 0.23656747
 0.83095051 0.68892029 0.81162129 0.97449862 0.36226004 0.31708618
 0.60789012 0.28580913 0.0974577  0.19500227 0.00327677 0.36742416
 0.7207724  0.15992063 0.09318239 0.74665179 0.53852039 0.21542668
 0.44164871 0.53954563 0.43732564 0.35105325 0.25430126 0.35431458
 0.31882305 0.33559333 0.08391902 0.47277899 0.79338764 0.32992248
 0.57165111 0.99682946 0.0845591  0.88125621 0.97579396 0.4897141
 0.57035648 0.02260736 0.73121659 0.86649956 0.99182359 0.56523804
 0.39077184 0.5404407  0.39173527 0.17757423 0.90569273 0.86815913
 0.34355835 0.59573835 0.2741421  0.58967185 0.723479   0.16477
 0.97366064 0.97397312 0.77617116 0.1333179  0.29890576 0.41726562
 0.77625386 0.00241168 0.2698286  0.24952094 0.48994875 0.38496755
 0.41026403 0.34821403 0.99350772 0.12775395 0.15760639 0.19944955
 0.07560515 0.77709007 0.43441109 0.19505781 0.66284387 0.98469385
 0.21949175 0.18866659 0.77583016 0.19858558 0.2528528 