# numpy常见用法

## 1.改变形状

In [2]:
import numpy as np
# 代码 2-21
arr = np.arange(12)  # 创建一维数组
print('创建的一维数组为：', arr)
print('新的一维数组为：\n', arr.reshape(3, 4))  # 设置数组的形状
print('数组维度为：', arr.reshape(3, 4).ndim)  # 查看数组维度

创建的一维数组为： [ 0  1  2  3  4  5  6  7  8  9 10 11]
新的一维数组为：
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
数组维度为： 2


## 2.平展

In [3]:
# 代码 2-22
arr = np.arange(12).reshape(3, 4)
print('创建的二维数组为：\n', arr)
print('数组展平后为：', arr.ravel())

创建的二维数组为：
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
数组展平后为： [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [4]:
# 代码 2-23
print('数组展平为：', arr.flatten())  # 横向展平
print('数组展平为：', arr.flatten('F'))  # 纵向展平

数组展平为： [ 0  1  2  3  4  5  6  7  8  9 10 11]
数组展平为： [ 0  4  8  1  5  9  2  6 10  3  7 11]


In [5]:
# 代码 2-24
arr1 = np.arange(12).reshape(3, 4)
print('创建的数组1为：\n', arr1)

arr2 = arr1*3
print('创建的数组2为：\n', arr2)
print('横向组合为：\n', np.hstack((arr1, arr2)))  # hstack函数横向组合

创建的数组1为：
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
创建的数组2为：
 [[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]
横向组合为：
 [[ 0  1  2  3  0  3  6  9]
 [ 4  5  6  7 12 15 18 21]
 [ 8  9 10 11 24 27 30 33]]


# python中axis=0 axis=1的理解

## 轴用来为超过一维的数组定义的属性，二维数据拥有两个轴：第0轴沿着行的垂直往下，第1轴沿着列的方向水平延伸。

注意看，官方对于0和1的解释是轴，也就是坐标轴。而坐标轴是有方向的，所以千万不要用行和列的思维去想axis，因为行和列是没有方向的，这样想会在遇到不同的例子时感到困惑。

 

根据官方的说法，1表示横轴，方向从左到右；0表示纵轴，方向从上到下。当axis=1时，数组的变化是横向的，而体现出来的是列的增加或者减少。

 

其实axis的重点在于方向，而不是行和列。具体到各种用法而言也是如此。当axis=1时，如果是求平均，那么是从左到右横向求平均；如果是拼接，那么也是左右横向拼接；如果是drop，那么也是横向发生变化，体现为列的减少。

当考虑了方向，即axis=1为横向，axis=0为纵向，而不是行和列，那么所有的例子就都统一了。


In [6]:
# 代码 2-25
print('纵向组合为：\n', np.vstack((arr1, arr2)))  # vstack函数纵向组合

# 代码 2-26
print('横向组合为：\n', np.concatenate((arr1, arr2), axis=1))  # concatenate函数横向组合
print('纵向组合为：\n', np.concatenate((arr1, arr2), axis=0))  # concatenate函数纵向组合

纵向组合为：
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]
横向组合为：
 [[ 0  1  2  3  0  3  6  9]
 [ 4  5  6  7 12 15 18 21]
 [ 8  9 10 11 24 27 30 33]]
纵向组合为：
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]


In [9]:
# 代码 2-27
arr = np.arange(16).reshape(4, 4)
print('创建的二维数组为：\n', arr)
print('横向分割为：\n', np.hsplit(arr, 2))  # hsplit函数横向分割

# 代码 2-28
print('纵向分割为：\n', np.vsplit(arr, 2))  # vsplit函数纵向分割

# 代码 2-29
print('横向分割为：\n', np.split(arr, 2, axis=1))  # split函数横向分割
print('纵向分割为：\n', np.split(arr, 2, axis=0))  # split函数纵向分割

创建的二维数组为：
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
横向分割为：
 [array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]
纵向分割为：
 [array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]
横向分割为：
 [array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]
纵向分割为：
 [array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]
