# 矩阵

### 1创建矩阵

In [1]:
# 代码 2-30
import numpy as np  # 导入NumPy库
matr1 = np.mat('1 2 3; 4 5 6; 7 8 9')  # 使用分号隔开数据
print('创建的矩阵为：\n', matr1)


matr2 = np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('创建的矩阵为：\n', matr2)

创建的矩阵为：
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
创建的矩阵为：
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


***

### 2将小矩阵组合成大举证 bmat函数的使用

In [2]:
# 代码 2-31
arr1 = np.eye(3)
print('创建的数组1为：\n', arr1)

arr2 = 3 * arr1
print('创建的数组2为：\n', arr2)

print('创建的矩阵为：\n', np.bmat('arr1 arr2; arr1 arr2'))

创建的数组1为：
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
创建的数组2为：
 [[3. 0. 0.]
 [0. 3. 0.]
 [0. 0. 3.]]
创建的矩阵为：
 [[1. 0. 0. 3. 0. 0.]
 [0. 1. 0. 0. 3. 0.]
 [0. 0. 1. 0. 0. 3.]
 [1. 0. 0. 3. 0. 0.]
 [0. 1. 0. 0. 3. 0.]
 [0. 0. 1. 0. 0. 3.]]


***

### 3形状相同的矩阵的运算

In [4]:
# 代码 2-32
matr1 = np.mat('1 2 3; 4 5 6; 7 8 9')  # 创建矩阵
print('创建的矩阵为：\n', matr1)

matr2 = matr1 * 3  # 矩阵与数相乘
print('创建的矩阵为：\n', matr2)
print('矩阵相加结果为：\n', matr1 + matr2)  # 矩阵相加
print('矩阵相减结果为：\n', matr1 - matr2)  # 矩阵相减
print('矩阵相乘结果为：\n', matr1 * matr2)  # 矩阵相乘
print('矩阵对应元素相乘结果为：\n', np.multiply(matr1, matr2))

创建的矩阵为：
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
创建的矩阵为：
 [[ 3  6  9]
 [12 15 18]
 [21 24 27]]
矩阵相加结果为：
 [[ 4  8 12]
 [16 20 24]
 [28 32 36]]
矩阵相减结果为：
 [[ -2  -4  -6]
 [ -8 -10 -12]
 [-14 -16 -18]]
矩阵相乘结果为：
 [[ 90 108 126]
 [198 243 288]
 [306 378 450]]
矩阵对应元素相乘结果为：
 [[  3  12  27]
 [ 48  75 108]
 [147 192 243]]


***

### 4矩阵的常见操作

In [5]:
matr3 = np.mat([[6, 2, 1], [1, 5, 2], [3, 4, 8]])
print('矩阵转置结果为：\n', matr3.T)  # 转置
print('矩阵的逆矩阵结果为：\n', matr3.I)  # 逆矩阵
print('矩阵的二维数组结果为：\n', matr3.A)  # 返回二维数组的视图

矩阵转置结果为：
 [[6 1 3]
 [2 5 4]
 [1 2 8]]
矩阵的逆矩阵结果为：
 [[ 0.18079096 -0.06779661 -0.00564972]
 [-0.01129944  0.25423729 -0.06214689]
 [-0.06214689 -0.10169492  0.15819209]]
矩阵的二维数组结果为：
 [[6 2 1]
 [1 5 2]
 [3 4 8]]


***

### 5+、-、*、/操作

使用条件 形状相同，操作每个元素。

In [2]:
# 代码 2-34
import numpy as np  # 导入NumPy库
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print('数组相加结果为：', x + y)  # 数组相加
print('数组相减结果为：', x - y)  # 数组相减
print('数组相乘结果为：', x * y)  # 数组相乘
print('数组相除结果为：', x / y)  # 数组相除
print('数组幂运算结果为：', x ** y)  # 数组幂运算

数组相加结果为： [5 7 9]
数组相减结果为： [-3 -3 -3]
数组相乘结果为： [ 4 10 18]
数组相除结果为： [0.25 0.4  0.5 ]
数组幂运算结果为： [  1  32 729]


***

### 6支持关系运算

In [4]:
# 代码 2-35
x = np.array([1, 3, 5])
y = np.array([2, 3, 4])
print('数组比较结果为：', x < y)
print('数组比较结果为：', x > y)
print('数组比较结果为：', x == y)
print('数组比较结果为：', x >= y)
print('数组比较结果为：', x <= y)
print('数组比较结果为：', x != y)

数组比较结果为： [ True False False]
数组比较结果为： [False False  True]
数组比较结果为： [False  True False]
数组比较结果为： [False  True  True]
数组比较结果为： [ True  True False]
数组比较结果为： [ True False  True]


***

### 7、ufunc函数的广播机制


（1）广播（Broadcasting）是指不同形状的数组之间执行算术运算的方式。  

 满足以下2个规则：  
     1）数组的某一维度等长  
     2）其中一个数组的某一维度为1     



（2）为了更好地使用广播机制，需要遵循以下4个原则。

1）让所有的输入数组向其中shape最长的数组看齐，shape中不足的部分通过在前面加1补齐。

2）输出数组的shape是输入数组shape的各个轴上的最大值。

3）如果输入数组的某个轴和输出数组的对应轴的长度相同或其长度为1，那么这个数组能够用于计算，否则系统将会出错。

4）当输入数组的某个轴的长度为1时，沿着此轴运算时使用此轴上的第一组值。



In [5]:
arr1 = np.array([[0, 0, 0], [1, 1, 1], [2, 2, 2], [3, 3, 3]])
print('创建的数组1为：\n', arr1)
print('数组1的shape为：', arr1.shape)
arr2 = np.array([1, 2, 3]) 
print('创建的数组2为：', arr2)
print('数组2的shape为：', arr2.shape)
print('数组相加结果为：\n', arr1 + arr2)

创建的数组1为：
 [[0 0 0]
 [1 1 1]
 [2 2 2]
 [3 3 3]]
数组1的shape为： (4, 3)
创建的数组2为： [1 2 3]
数组2的shape为： (3,)
数组相加结果为：
 [[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]


In [6]:
arr1 = np.array([[0, 0, 0], [1, 1, 1], [2, 2, 2], [3, 3, 3]])
print('创建的数组1为：\n', arr1)
print('数组1的shape为：', arr1.shape)

arr2 = np.array([1, 2, 3, 4]).reshape((4, 1))
print('创建的数组2为：\n', arr2)

print('数组2的shape为：', arr2.shape)
print('数组相加结果为：\n', arr1 + arr2)

创建的数组1为：
 [[0 0 0]
 [1 1 1]
 [2 2 2]
 [3 3 3]]
数组1的shape为： (4, 3)
创建的数组2为：
 [[1]
 [2]
 [3]
 [4]]
数组2的shape为： (4, 1)
数组相加结果为：
 [[1 1 1]
 [3 3 3]
 [5 5 5]
 [7 7 7]]
