# 利用Numpy进行统计分析

### save以二进制形式保存文件

In [3]:
# 代码 2-39
import numpy as np  # 导入NumPy库
arr = np.arange(100).reshape(10, 10)  # 创建一个数组
np.save('./data/save_arr', arr)  # 保存数组
print('保存的数组为：\n', arr)

保存的数组为：
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


保存多个数组

In [4]:
# 代码 2-40
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.arange(0, 1.0, 0.1)
np.savez('./data/savez_arr', arr1, arr2)
print('保存的数组1为：', arr1)
print('保存的数组2为：', arr2)

保存的数组1为： [[1 2 3]
 [4 5 6]]
保存的数组2为： [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


***

### load 二进制文件读取

In [6]:
# 代码 2-41
# 读取含有单个数组的文件
loaded_data = np.load('./data/save_arr.npy')  
print('读取的数组为：\n', loaded_data)
 # 读取含有多个数组的文件
loaded_data1 = np.load('./data/savez_arr.npz') 
print('读取的数组1为：\n', loaded_data1['arr_0'])
print('读取的数组2为：', loaded_data1['arr_1'])

读取的数组为：
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
读取的数组1为：
 [[1 2 3]
 [4 5 6]]
读取的数组2为： [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


***

### 文件的存储与读取

(1)写文件

在实际的数据分析任务中，更多地是使用文本格式的数据，如TXT或CSV格式，因此通常会使用savetxt函数、loadtxt函数和genfromtxt函数执行对文本格式数据的读取任务。   
savetxt函数可将数组写到以某种分隔符隔开的文本文件中，其基本使用格式如下。  


参数fname接收str，表示文件名。   
参数X接收array_like，表示数组数据。    
参数delimiter接收str，表示数据分隔符。    


In [10]:
# 代码 2-42
arr = np.arange(0, 12, 0.5).reshape(4, -1)
print('创建的数组为：\n', arr)

# fmt='%d'表示保存为整数
np.savetxt('./data/arr1.txt', arr, fmt='%f', delimiter=',')

创建的数组为：
 [[ 0.   0.5  1.   1.5  2.   2.5]
 [ 3.   3.5  4.   4.5  5.   5.5]
 [ 6.   6.5  7.   7.5  8.   8.5]
 [ 9.   9.5 10.  10.5 11.  11.5]]


（2）读文件

loadtxt函数执行的是相反的操作，即将文件加载到一个二维数组中，其基本使用格式如下。



loadtxt函数的常用参数主要有两个，分别是fname和delimiter。   
参数fname接收str，表示需要读取的文件、文件名或生成器。   
参数delimiter接收str，表示用于分隔数值的分隔符。   


In [11]:
# 读入的时候也需要指定逗号分隔
loaded_data = np.loadtxt('./data/arr1.txt',dtype=float, delimiter=',') 
print('读取的数组为：\n', loaded_data)

读取的数组为：
 [[ 0.   0.5  1.   1.5  2.   2.5]
 [ 3.   3.5  4.   4.5  5.   5.5]
 [ 6.   6.5  7.   7.5  8.   8.5]
 [ 9.   9.5 10.  10.5 11.  11.5]]


（3）genfromtxt读文件

genfromtxt函数和loadtxt函数相似，只不过genfromtxt函数面向的是结构化数组和缺失数据。   
genfromtxt函数通常使用的参数有3个。   
即用于存放数据的文件名参数“fname”。   
用于分隔的字符参数“delimiter”。   
是否含有列标题参数“names”。  


In [12]:
# 代码 2-43
loaded_data = np.genfromtxt('./data/arr1.txt', delimiter=',')
print('读取的数组为：\n', loaded_data)

读取的数组为：
 [[ 0.   0.5  1.   1.5  2.   2.5]
 [ 3.   3.5  4.   4.5  5.   5.5]
 [ 6.   6.5  7.   7.5  8.   8.5]
 [ 9.   9.5 10.  10.5 11.  11.5]]
